### PR TITLE
Resolving MACOS speed issues.

### PR DESCRIPTION
**Pull request by lmarchen**
Resolved MACOS speed issues by changing "ifx" options:

1. removed -g
2. removed -check bounds,stack (this one slowed down MACOS)
3. added -Ofast

Also resolved issue with bash export command which were overwriting previous paths set by sourcing intel compiler bash file.

### CODE REVIEW

**Comment by lmarchen** [comment]
Scott would you mind pulling from comp_opt and testing when you are able to very this works?

**Comment by sabasinger** [comment]
It seems to me that -check bounds,stack is still in macos_f90/Makefile line 67.  When I compiled, I saw it.

**Comment by lmarchen** [comment]
I had made a mistake, I put the Makefile in the wrong location (I put it under the macos folder rather than under macOS_f90). That mistake was corrected and now you should be fine pulling and compiling.

**Comment by sabasinger** [comment]
It looks faster than the one I benchmarked against before, completing 1024 size OPD in 5.55 s, compared to 14s for benchmark and 43s for non-optimized version.

**Review by sabasinger — APPROVED** [review]
The compiler optimization options look good

**Pull request merged**
