### PR TITLE
added -traceback -check bounds,stack to FC alias

### PR DESCRIPTION
**Pull request by sabasinger**
I added -traceback -check bounds,stack to FC alias in macos_f90/Makefile.  This is something Luis sent to me this morning.  This is a test to do a pull and merge request

### CODE REVIEW

**Comment by lmarchen** [comment]
Scott,

Ok thanks!

Luis

**Review by lmarchen — COMMENTED** [review]
We added these option while compiling macos release 3.36.

**Review by lmarchen — APPROVED** [review]
I forgot to approve the merging.

**Comment by sabasinger** [comment]
Closes #3

**Pull request merged**
